### ISSUE TITLE
fatal error: tbb/task_scheduler_init.h: There is no file or directory

### ISSUE THREAD

**Issue by MagiSuCoder** [eXascaleInfolab/GenConvNMI#4]
There is another question as follows:
when i input  "make release",the erroe messages are:
test -d bin/Release || mkdir -p bin/Release
test -d obj/Release/src || mkdir -p obj/Release/src
test -d obj/Release || mkdir -p obj/Release
g++ -Wnon-virtual-dtor -Wredundant-decls -Wcast-align -Wundef -Wunreachable-code -Wmissing-include-dirs -Weffc++ -Wzero-as-null-pointer-constant -std=c++14 -fexceptions -fstack-protector-strong -D_FORTIFY_SOURCE=2 -march=core2 -fomit-frame-pointer -O3 -Wfatal-errors -Iinclude -Ishared -Ishared_daoc -c src/calculate_till_tolerance.cpp -o obj/Release/src/calculate_till_tolerance.o
src/calculate_till_tolerance.cpp:1:86: **fatal error: tbb/task_scheduler_init.h: There is no file or directory**
compilation terminated.
Makefile:131: recipe for target 'obj/Release/src/calculate_till_tolerance.o' failed
make: *** [obj/Release/src/calculate_till_tolerance.o] Error 1
 So what should i do ?looking forward to your replay!

_Originally posted by @MagiSuCoder in https://github.com/eXascaleInfolab/GenConvNMI/issues/3#issuecomment-720332051_

**Comment by luav** [comment]
Hi @MagiSuCoder,
you should [install all the requirements](https://github.com/eXascaleInfolab/GenConvNMI#requirements) before compiling this project.
`tbb/task_scheduler_init.h` is a header from the library `libtbb2`, which is specified in the dependencies. You should install either `libtbb2` or `libtbb2-dev` among the requirements to compile the source code of this project.

You are welcome to close this issue if this answer solves your problem. Otherwise, can you please specify the `libtbb2` version installed in your system and the way you installed it?

**Comment by MagiSuCoder** [comment]
Hi, i installed again the libtbb2-dev and it worked, and i see the gecmi in  bin/Release/
but when i execute the command:gecmi file1 file2.
the messages shows that **gecmi:Linux did not find the command**.
so what's wrong with it?

**Comment by luav** [comment]
You should learn how Linux/Unix/POSIX execute commands. `$ gecmi` is searched in the system `PATH`, but you would like to execute it from the specified path: `$ ./gecmi <params>` to run gecmi from the current directory (if you are in the `bin/Release/` dir) or `$ <path>/gecmi <params>` to run it from the specified dir=`<path>`.

**Comment by MagiSuCoder** [comment]
Thank you very much for your answer!
